import matplotlib.pyplot as plt
import numpy as np
import torch


def accuracy_plot(accuracy_list):
    plt.plot(range(1,len(accuracy_list)+1), accuracy_list, 'c')
    plt.plot(range(1,len(accuracy_list)+1), accuracy_list,'b.')
    plt.hlines(np.average(accuracy_list),0,len(accuracy_list)+1, 'r')
    plt.ylabel("Accuracy")
    plt.xlabel("Iteration")
    #plt.xticks(range(1,len(accuracy_list),2))
    plt.title("Accuracy of models generated by the controller")
    plt.savefig("plot/acc_plot.png")
    plt.show()

def loss_plot(loss_list):
    print(loss_list)
    #loss_list = loss_list.detach()
    plt.plot(range(1, len(loss_list) + 1), loss_list, 'c')
    plt.plot(range(1, len(loss_list) + 1), loss_list, 'b.')
    plt.hlines(np.average(loss_list), 0, len(loss_list) + 1, 'r')
    plt.ylabel("Loss")
    plt.xlabel("Iteration")
    # plt.xticks(range(1,len(accuracy_list),2))
    plt.title("Loss of the controller")
    plt.savefig("plot/loss_plot.png")
    plt.show()